# Generated by Django 5.1 on 2025-05-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_id', models.BigIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('create_time', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
