# Generated by Django 5.1 on 2025-05-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
